Init app
toledompm/devops-app pull request #1
Opened 2021-04-01 00:54 UTC by toledompm

2021-04-05 23:43 UTC, jasondavindev requested changes

2021-04-05 23:43 UTC, jasondavindev commented on src/index.ts
> +app.listen(PORT, () => console.log('Server listening on port', PORT));
Escreve em javascript, parça

2021-04-05 23:58 UTC, toledompm commented on src/index.ts
> +app.listen(PORT, () => console.log('Server listening on port', PORT));
:sob:

2021-04-06 00:00 UTC, toledompm commented on package.json
> +    "lint:fix": "npx eslint ./**/*.js --fix",
```suggestion
    "lint": "prettier --check .",
    "lint:fix": "prettier --write .",
```

2021-04-06 00:12 UTC, jasondavindev approved these changes

2021-04-06 00:26 UTC, NicolasFujisawa approved these changes

2021-04-06 00:34 UTC, merged